---

- name: Beginning Framework Level Software Provisioning...
  pause:
    prompt: "Do you wish to proceed or pause? Press Ctrl+C to pause/re-evaluate or do nothing to automatically continue..."
    seconds: 10


# - name: Scan Project Directory
#   find:
#     paths: "{{ system_app_directory }}"
#     recurse: yes
#   register: files_to_delete

# - name: Empty Project Directory
#   file:
#     path: "{{ system_app_directory }}"
#     state: absent
#   loop: "{{ files_to_delete.files }}"


- name: Perform Laravel Provisioning
  include_tasks: frameworks/laravel.yml
  when: "'laravel' in provisioning_software_framework"


- name: Perform Wordpress Provisioning
  include_tasks: frameworks/wordpress.yml
  when: "'wordpress' in provisioning_software_framework"

