---

- name: Beginning System Level Software Provisioning...
  pause:
    prompt: "Do you wish to proceed? Press Enter to continue or Ctrl+C to re-evaluate"
    seconds: 10


- name: Creates DevOps Directories
  file:
    path: "{{ '/var/www/' + item.dir }}"
    state: directory
    owner: "{{ instance_user | default('ubuntu') }}"
    group: "{{ instance_user | default('ubuntu') }}"
    mode: "{{ item.permission }}"
  loop:
    - { dir: 'github-tmp', permission: 'u=rwx,g=rx,o=rx' }
    - { dir: 'env-files', permission: 'u=rwx,g=rx,o=rx' }


- name: Define System Project Path
  set_fact:
    system_project_directory: "/var/www/{{ project }}"

- name: Update System Project Path
  set_fact:
    system_project_directory: "/var/www/{{ project }}/public"
  when: provisioning_type == "app" and "'php' in provisioning_software_system"



#------------------------------------------------------
# Create Directories
#------------------------------------------------------
- name: Project VM - Creates Project Directory
  file:
    path: "{{ system_project_directory }}"
    state: directory
    owner: "{{ instance_user | default('ubuntu') }}"
    group: "{{ instance_user | default('ubuntu') }}"
  when: provisioning_type == "app"

- name: Project VM - Creates Project Directory Index (PHP Apps)
  template:
    src: "templates/php.j2"
    dest: "{{ system_project_directory + '/index.php' }}"
  vars:
    template_domain: "{{ domain }}"
    template_port: ""
  when: provisioning_type == "app" and "'php' in provisioning_software_system"


#------------------------------------------------------
# Extract IAAS Keys and/or Secrets from Credentials
#------------------------------------------------------
- name: Extract AWS_ACCESS_KEY_ID from Credentials
  set_fact:
    aws_access_key_id: "{{ infrastructure_aws_access_key_id }}"
  when: infrastructure_iaas_provider == "aws"

- name: Extract AWS_ACCESS_KEY_SECRET from Credentials
  set_fact:
    aws_access_key_secret: "{{ infrastructure_aws_access_key_secret }}"
  when: infrastructure_iaas_provider == "aws"

- name: Extract AWS_ACCESS_REGION from Credentials
  set_fact:
    aws_region: "{{ infrastructure_aws_region }}"
  when: infrastructure_iaas_provider == "aws"

- name: Extract DIGITAL OCEAN TOKEN from Credentials
  set_fact:
    do_token: "{{ infrastructure_do_token }}"
  when: infrastructure_iaas_provider == "do"


#------------------------------------------------------
# Install System Software for PHP Apps
#------------------------------------------------------

- name: Project Compute - Install PHP Versions
  include_role:
    name: geerlingguy.php-versions
  vars:
    php_version: "{{ php_version_number }}"
  when: provisioning_type == "app" and "'php' in provisioning_software_system"

- name: Project Compute - Install PHP
  include_role:
    name: geerlingguy.php
  vars:
    php_packages: "{{ php_packages_list }}"
    php_enable_php_fpm: true
    php_fpm_state: started
    php_fpm_enabled_on_boot: true
    php_fpm_handler_state: restarted
    php_webserver_daemon: "nginx"
    php_default_version_debian: "{{ php_version_number }}"
    php_version: "{{ php_version_number }}"
    #php_sendmail_path: "{{ mail_mailhog_path + '/mhsendmail' }}"
  when: provisioning_type == "app" and "'php' in provisioning_software_system"

- name: Project Compute - Install Composer
  include_role:
    name: geerlingguy.composer
  when: provisioning_type == "app" and "'php' in provisioning_software_system"

- name: Project Compute - Install Nginx Web Server (PHP)
  include_role:
    name: geerlingguy.nginx
  vars:
    nginx_vhosts:
      - listen: "80"
        server_name: "{{ vhost_item.server_name }}"
        root: "{{ system_project_directory }}"
        index: "index.php index.html index.htm"
        access_log: "/var/log/nginx/access_{{ vhost_item.domain }}.log"
        error_log: "/var/log/nginx/error_{{ vhost_item.domain }}.log"
        state: "present"
        template: "{{ nginx_vhost_template }}"
        filename: "{{ vhost_item.domain }}.conf"
        extra_parameters: |
          location / {
              try_files $uri $uri/ /index.php$is_args$args;

              # default cors
              add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
              add_header Access-Control-Allow-Origin "$http_origin" always;
              add_header Access-Control-Allow-Credentials "true" always;
              add_header Access-Control-Allow-Methods "OPTIONS, DELETE, POST, GET, PATCH, PUT" always;
              #add_header Access-Control-Allow-Headers "Content-Type";
              add_header Access-Control-Allow-Headers "Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With" always;
              # required to be able to read Authorization header in frontend
              #add_header 'Access-Control-Expose-Headers' 'Authorization' always;

          }

          # protect ENV files
          location ~ /\.env {
              deny all;
          }
          
          location ~ \.php$ {
              try_files $uri /index.php =404;
              fastcgi_split_path_info ^(.+\.php)(/.+)$;
              fastcgi_pass {{ php_cgi }};
              fastcgi_index index.php;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include fastcgi_params;
          }
  loop:
    - { domain: "{{ domain }}", dir: "{{ project }}", server_name: "{{ domain }} {{  '*.' + domain }}" }
  loop_control:
    loop_var: vhost_item
  when: provisioning_type == "app" and "'php' in provisioning_software_system"


#------------------------------------------------------
# Install SSL System Software
#------------------------------------------------------
- name: Install SSL
  include_role:
    name: geerlingguy.certbot
  vars:
    certbot_install_method: snap
    certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    certbot_auto_renew_hour: "3"
    certbot_auto_renew_minute: "30"
    certbot_auto_renew_options: "--quiet --no-self-upgrade"
    certbot_create_if_missing: true
    certbot_create_method: standalone
    certbot_certs:
      - email: "dev@hostville.website"
        webroot: "{{ system_project_directory }}"
        domains:
          - "{{ domain }}"
    certbot_create_standalone_stop_services:
      - nginx
  when: provisioning_type == "app"


# - name: Install Wildcard SSL (AWS Route53 Plugin)
#   shell: |
#     sudo snap set certbot trust-plugin-with-root=ok
#     sudo snap install certbot-dns-route53
#     sudo AWS_ACCESS_KEY_ID="{{ aws_access_key_id }}" AWS_SECRET_ACCESS_KEY="{{ aws_access_key_secret }}" AWS_DEFAULT_REGION="{{ aws_region }}" certbot certonly --dns-route53 -d {{ domain }} -d *.{{ domain }} -d *.store.{{ domain }} --agree-tos -m dev@hostville.website
#     sudo AWS_ACCESS_KEY_ID="{{ aws_access_key_id }}" AWS_SECRET_ACCESS_KEY="{{ aws_access_key_secret }}" AWS_DEFAULT_REGION="{{ aws_region }}" certbot certonly --dns-route53 -d core.{{ domain }} --agree-tos -m dev@hostville.website
#   register: wildcard_output
#   async: 300
#   poll: 30
#   when: infrastructure_iaas_provider == "aws"

# - name: Install Wildcard SSL (Digital Ocean)
#   shell: |
#     sudo snap set certbot trust-plugin-with-root=ok
#     sudo snap install certbot-dns-digitalocean
#     echo "dns_digitalocean_token = {{ do_token }}" | sudo tee /var/www/digitalocean.ini
#     sudo chmod 600 /var/www/digitalocean.ini
#   register: wildcard_output
#   async: 300
#   poll: 30
#   when: iaas_provider == "do"

# - name: Install Wildcard SSL (Digital Ocean Plugin)
#   expect:
#     command: sudo certbot certonly --dns-digitalocean --dns-digitalocean-credentials /var/www/digitalocean.ini -d {{ domain }} -d *.{{ domain }} --agree-tos -m dev@hostville.website
#     responses:
#         "You have an existing certificate ": "1"
#         "share your email address with the Electronic Frontier Foundation,": "N"
#   become: true
#   ignore_errors: true
#   async: 300
#   poll: 30
#   when: iaas_provider == "do"


- name: Project Compute - Install Nginx Web Server (PHP) (Secure)
  include_role:
    name: geerlingguy.nginx
  vars:
    nginx_vhosts:
      - listen: "443 ssl http2"
        server_name: "{{ vhost_ssl_item.server_name }}"
        root: "{{ system_project_directory }}"
        index: "index.php index.html index.htm"
        access_log: "/var/log/nginx/access_{{ vhost_ssl_item.domain }}_ssl.log"
        error_log: "/var/log/nginx/error_{{ vhost_ssl_item.domain }}_ssl.log"
        state: "present"
        template: "{{ nginx_vhost_template }}"
        filename: "{{ vhost_ssl_item.domain }}_ssl.conf"
        extra_parameters: |
          location / {
              try_files $uri $uri/ /index.php$is_args$args;

              # default cors
              add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
              add_header Access-Control-Allow-Origin "$http_origin" always;
              add_header Access-Control-Allow-Credentials "true" always;
              add_header Access-Control-Allow-Methods "OPTIONS, DELETE, POST, GET, PATCH, PUT" always;
              #add_header Access-Control-Allow-Headers "Content-Type";
              add_header Access-Control-Allow-Headers "Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With" always;
              # required to be able to read Authorization header in frontend
              #add_header 'Access-Control-Expose-Headers' 'Authorization' always;

          }

          # protect ENV files
          location ~ /\.env {
              deny all;
          }
          
          location ~ \.php$ {
              try_files $uri /index.php =404;
              fastcgi_split_path_info ^(.+\.php)(/.+)$;
              fastcgi_pass {{ php_cgi }};
              fastcgi_index index.php;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include fastcgi_params;
          }

          ssl_certificate {{ '/etc/letsencrypt/live/' + vhost_ssl_item.domain + '/fullchain.pem' }};
          ssl_certificate_key {{ '/etc/letsencrypt/live/' + vhost_ssl_item.domain + '/privkey.pem' }};
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;
  loop:
    - { domain: "{{ domain }}", dir: "{{ project }}", server_name: "{{ domain }} {{  '*.' + domain }}" }
  loop_control:
    loop_var: vhost_ssl_item
  when: provisioning_type == "app" and "'php' in provisioning_software_system"

#------------------------------------------------------
# Install System Software for Databases
#------------------------------------------------------

- name: Project Compute - Install MySQL
  include_role:
    name: geerlingguy.mysql
    apply:
      become: yes
  vars:
    mysql_root_username: "root"
    mysql_root_password: "{{ mysql_root_pass }}"


- name: Create new Databases
  community.mysql.mysql_db:
    name:
      - "sample_db"
    state: present


- name: Create database user with database privileges
  community.mysql.mysql_user:
    host: localhost
    name: "root"
    password: "{{ mysql_pass }}"
    priv:
      "sample_db.*": 'ALL,GRANT'
    state: present


- name: Re-Grant Database Privileges
  shell: |
    mysql -u {{ root }} -p{{ mysql_root_pass }} -e "GRANT ALL PRIVILEGES ON {{ db_item.db }}.* TO '{{ db_item.usr }}'@'localhost'; FLUSH PRIVILEGES;"
  loop:
    - { db: "sample_db", usr: "{{ mysql_user }}" }
  loop_control:
    loop_var: db_item
  ignore_errors: true
  become: true


- name: Install & Configure Supervisor for Queue (PHP Laravel Apps)
  include_role:
    name: geerlingguy.supervisor
  vars:
    supervisor_programs:
      - name: 'modullo-worker'
        command: sudo php /var/www/{{ project }}/artisan queue:work redis --sleep=3 --tries=3
        state: present
        configuration: |
          autostart=true
          autorestart=true
          startretries=3
          startsecs=1
          redirect_stderr=true
          stdout_logfile=/var/www/{{ project }}/storage/logs/modullo-worker.log
          user=www-data
          killasgroup=true
          stopasgroup=true
  when: provisioning_type == "app" and "'php' in provisioning_software_system" and "'laravel' in provisioning_software_framework"