---

- name: Beginning OS Level Software Provisioning
  pause:
    prompt: "Do you wish to proceed? This pause will last 10 seconds. Press Enter to continue or Ctrl+C to skip this provisioning."
    seconds: 10


- name: Install Necessary System Software
  apt:
    name: "{{ software_system }}"
    update_cache: yes
  become: yes
  #ignore_errors: True
  async: 600
  poll: 30

- name: Install Certbot via Snap
  snap:
    name: certbot
    classic: yes



- name: Install python packages
  ansible.builtin.pip:
    name:
      - bcrypt
